#!/bin/bash

export GO15VENDOREXPERIMENT=1

# save env
OLD_GOPATH=$GOPATH
export GOPATH=$(pwd)

# all dirs
DIRS="cacher cli"

# fix vendor path
for DIR in $DIRS; do
    ln -sf $(pwd)/vendor src/$DIR
done

# build
for DIR in $DIRS; do
    go build $DIR
done

# move bins
mkdir -p bin
mv $DIRS bin

# restore
export GOPATH=$OLD_GOPATH
